### ISSUE TITLE
Mica Discord does not start up.

### ISSUE THREAD

**Issue by hedhehd** [Get0457/Mica-Discord#1]
I do have discord installed. Do I need to uninstall it?

**Comment by Get0457** [comment]
No, you don't have to

**Comment by Get0457** [comment]
Did you download Evergreen WebView2 and .NET 6 Desktop Runtime and installed already?
- Evergreen https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
- .NET 6 Desktop Runtime https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by hedhehd** [comment]
Yes

**Comment by hedhehd** [comment]
Do I need to restart?

**Comment by Get0457** [comment]
You should try that

**Comment by hedhehd** [comment]
I did no effect

**Comment by Get0457** [comment]
What windows build?

**Comment by hedhehd** [comment]
22621.160 Beta channel

**Comment by hedhehd** [comment]
Insider

**Comment by Get0457** [comment]
Did you install using setup.exe file?

**Comment by Get0457** [comment]
Double-clicking MicaDiscord.exe might not work as expected

**Comment by hedhehd** [comment]
Yep

**Comment by hedhehd** [comment]
I did install through setup.exe

**Comment by Get0457** [comment]
Please double click setup.exe and then install

**Comment by hedhehd** [comment]
It says that it is installed already

**Comment by hedhehd** [comment]
So what can be the problem?

**Comment by Get0457** [comment]
Try running the program from start menu

**Comment by hedhehd** [comment]
I loads for 4-5 seconds then does not open up

**Comment by Get0457** [comment]
Can you go to Event Viewer -> Windows Log -> Application

**Comment by Get0457** [comment]
Then find the latest error from MicaDiscord.exe

**Comment by hedhehd** [comment]
Application: MicaDiscord.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: No match was found for the specified key in the index. (0x80070491)
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.Windows.ApplicationModel.DynamicDependency.BootstrapCS.AutoInitialize.AccessWindowsAppSDK()
   at <Module>..cctor()

**Comment by hedhehd** [comment]
Faulting application name: MicaDiscord.exe, version: 1.9.0.0, timestamp: 0x622f78e0
Faulting module name: unknown, version: 0.0.0.0, timestamp: 0x00000000
Exception code: 0x80131623
Error offset: 0x00007ff7efe62f40
Faulting process ID: 0x0x834
Faulting application start time: 0x0x1D88468F7CBA902
Faulting application path: C:\Users\serap\AppData\Local\Apps\2.0\YZO5791V.AVY\DY03ZYA9.R88\mica..tion_0000000000000000_0001.000a_697392510049cab8\MicaDiscord.exe
Faulting module path: unknown
Report ID: 4d0d93a3-f284-4558-ad35-8dc6a7bd415f
Full name of the faulting package:
Application ID relative to the faulty package:

**Comment by Get0457** [comment]
Anyways, I think you are using [publish.win10.patch.win11.zip](https://github.com/Get0457/Mica-Discord/releases/download/v1.10.2/publish.win10.patch.win11.zip), right?

**Comment by hedhehd** [comment]
Yes

**Comment by hedhehd** [comment]
Because I'm in windows 11

**Comment by Get0457** [comment]
I think I know now.
Please download and install Windows App SDK 1.0.3 (Runtime Installer)
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by Get0457** [comment]
If this works I will go and edit the release note

**Comment by hedhehd** [comment]
1.1 or 1.0?

**Comment by Get0457** [comment]
1.0

**Comment by Get0457** [comment]
In that section you can find 1.0.3 download

**Comment by hedhehd** [comment]
IT WORKED THANK YOU

**Comment by hedhehd** [comment]
Please update the readme and release notes to include this:

Windows App SDK 1.0.3: https://aka.ms/windowsappsdk/1.0/1.0.3/windowsappruntimeinstall-1.0.3-x64.exe
