### ISSUE TITLE
Mica efffect doesn't seems like want to show up

### ISSUE THREAD

**Issue by ran-yakumo-eee** [Get0457/Mica-Discord#3]
So i installed all the programs listed on readme.md but the Mica effect (so is any other backdrop types) doesn't wanna show up smh. This is the screenshot of it
![image](https://user-images.githubusercontent.com/84310373/182768858-2dbf09ab-2be5-453c-b2f7-0d2f663fa137.png)

**Comment by Get0457** [comment]
Hi, what windows build are you using?

**Comment by Get0457** [comment]
Additionally, can you take a screenshot of the settings page? Thank you!

**Comment by ran-yakumo-eee** [comment]
![image](https://user-images.githubusercontent.com/84310373/182876658-92431748-95af-43d0-8fed-c387f9865b1a.png)
Hi, here's the setting page
I'm using 21H2 non-insider (maybe this is the reason?)

**Comment by ran-yakumo-eee** [comment]
Oh i forgot, the build number is 22000.675

**Comment by Get0457** [comment]
I'm guessing the Mica effect does not apply in the Settings Menu too, right?

Anyways, "Enable Fluent Design" needs to be on for the Mica effect to work. However, if the Mica effect does not work in Settings and the title bar without this option, this would not work either.

**Comment by Get0457** [comment]
Anyways, may I ask which .zip file did you use? (The file name that you have downloaded)

**Comment by Get0457** [comment]
And lastly, can you try downloading and running SystemBackdropTypes-x64.exe from [SystemBackdropTypes](https://github.com/dongle-the-gadget/SystemBackdropTypes/releases/tag/revision-1) repository? If the Mica effect does not work there, it means it will be very likely that it will not work here.

**Comment by Get0457** [comment]
I'll add that information to Readme.

**Comment by ran-yakumo-eee** [comment]
Alright, thank you. 
I used the publish.win10or11.zip from the latest version. Also i installed from the setup.exe file, if that's also the information you need.

**Comment by Get0457** [comment]
Thank you! Although I am sorry that it does not work in non-insider version. I'll close the issue now!

**Comment by ran-yakumo-eee** [comment]
![image](https://user-images.githubusercontent.com/84310373/183083632-2cfdf5a8-f65e-4a2e-81f4-8054e229941c.png)
![image](https://user-images.githubusercontent.com/84310373/183083677-65397c2a-5433-40ec-9180-bda2d2a9b103.png)
Oh wait this one is actually not very related but is this perhaps hidden or moved to a new directory?

**Comment by Get0457** [comment]
Oh yes it is. Thanks! I'll fix that later.

**Comment by ran-yakumo-eee** [comment]
![image](https://user-images.githubusercontent.com/84310373/183290266-3151daaa-d3a7-4436-8907-fd4be04f1085.png)
UPDATE: after turn off fluent design and set the backdrop type to default, although hard to visible but it ACTUALLY give an semi-mica looking and also change the theme, in a way

**Comment by ran-yakumo-eee** [comment]
quite brain-hurting but yes it works smh

**Comment by ran-yakumo-eee** [comment]
and yes i still use the same version when i opened this issue

**Comment by ran-yakumo-eee** [comment]
or if this is acrylic i don't know to be honest

**Comment by Get0457** [comment]
Turning off Fluent Design should not modify the look of discord so that is not supposed to happen, so I think that might be a bug. However, I cannot replicate the bug.
