### ISSUE TITLE
Lisence Thing

### ISSUE THREAD

**Issue by StaticGamerYT-India** [Get0457/Mica-Discord#4]
![image](https://user-images.githubusercontent.com/77852984/198709909-98277b1c-c94c-41d5-9706-ca9df316462e.png)
hey i got this thing up on when clicking the uwp file

**Comment by foursplaysroblox** [comment]
![image](https://user-images.githubusercontent.com/82078139/198934962-f74d51af-c199-458d-8b7b-55d09e525ff1.png)
i got it from rise media player

**Comment by Get0457** [comment]
^
Try to follow those instructions. Thanks @foursplaysroblox
