### ISSUE TITLE
Use the old discord Icon

### ISSUE THREAD

**Issue by foursplaysroblox** [Get0457/Mica-Discord#5]
can you use the old discord icon?
![image](https://user-images.githubusercontent.com/82078139/198935248-6ba0beb5-7167-4151-ae91-76644b49977f.png)
![image](https://user-images.githubusercontent.com/82078139/198935289-7f17217c-d716-4faf-a6af-e5be7b3a3718.png)
![image](https://user-images.githubusercontent.com/82078139/198935312-76c189ee-8514-4b32-a223-9f0ca1730bfc.png)

**Comment by Get0457** [comment]
For the discord logo itself, I would say that the new logo looks relatively close to the old one, and it is hard to change all of them. I won't do it, but PR about this is welcomed.

For the `DISCORD` text
![image](https://user-images.githubusercontent.com/41405393/199820585-3feb5080-38bc-4dd1-af70-238a366df245.png)
I did not see the new version used anywhere in the app. In the Discord Client, it is placed on the title bar. However, Mica Discord does not use the same title bar so I don't think there is anything to change.
