### ISSUE TITLE
DOES NOT ALLOW THE INSTALLATION OF THE APPLICATION.

### ISSUE THREAD

**Issue by HelderRocket** [Get0457/Mica-Discord#8]
When downloading the installation package, you get an error saying that the publisher certificate of this application package could not be verified, making it impossible to proceed with the installation.

![image](https://user-images.githubusercontent.com/104467221/208174442-9e5eabb4-8255-4b22-908b-071213f52d1d.png)

**Comment by Doda94** [comment]
As a temporary fix you can find the certificate in the details of the mica discord file and you can install it from there

**Comment by foursplaysroblox** [comment]
![image](https://user-images.githubusercontent.com/82078139/226299029-f1b752ad-e66b-43b2-9e34-73dd53d1b21e.png)

**Comment by pdimu** [comment]
the certificate (.cer) is expired and i can't install mica discord @GetGet99
